### ISSUE TITLE
Could I use this in my project ?

### ISSUE THREAD

**Issue by misogihagi** [wizeline/serverless-amplify-plugin#10]
hello.
To be honest, the document is briefly writing for me, I couldn't judge whether effective or not.
my project is simple amplify stack like:
```
├─backend
│  └─amplify
│      └─backend
│          ├─api
│          │   └─graphql
│          └─function
│              ├─lambda1
│              │  ├─dist
│              │  └─src
│              └─lambda2
│              │  ├─dist
│              │  └─src
└─frontend
    ├─dist
    └─src
```

So what I want do is wrapping AWS Amplify with Serverless framework. 
Is it capable?

**Comment by brettstack** [comment]
If you're already using the Amplify CLI you should use their method of setting up Amplify Console hosting

**Comment by misogihagi** [comment]
You mean serverless-amplify-plugin helps developers who manage to do without Amplify CLI ?

**Comment by brettstack** [comment]
Yes, it's a plugin for deploying websites to Amplify Console https://aws.amazon.com/amplify/console/. If you're using Amplify CLI, you should use their built in method. If you're using Serverless Framework, you can use this plugin.

**Comment by misogihagi** [comment]
Oh.. I wish If Amplify and Serverless Framework could coexist, it would be amazing developing experience.
if impossible, I will look for another way for multi-cloud.
